os_images role
stackhpc/ansible-collection-openstack pull request #19
Opened 2023-11-28 14:10 UTC by scrungus

2023-11-29 10:00 UTC, markgoddard requested changes

2023-11-29 10:00 UTC, markgoddard commented on roles/os_images/tasks/promote.yml
> +      - item.name in promote_list.openstack_images | map(attribute='name') | list
The return value changed in openstack.cloud.image_info
```suggestion
      - item.name in promote_list.images | map(attribute='name') | list
```

2023-11-29 14:37 UTC, markgoddard submitted a review, later dismissed

2023-11-29 15:08 UTC, scrungus commented
@markgoddard I didn't realise we had the change to `openstack.cloud.image` module in here, I thought it was in #20 . The new module requires `openstacksdk > 1.0`, so upper constraints needs to be updated: 

```
# Use Antelope upper constraints as openstacksdk 1.0.1 and openstackclient 6.2.0 are required
os_images_upper_constraints_file: https://releases.openstack.org/constraints/upper/2023.1
```

Do you want to add this to this PR or just merge this one and #20 as well?

2023-11-29 17:06 UTC, scrungus commented
done

2023-11-30 10:33 UTC, markgoddard approved these changes

2023-11-30 10:34 UTC, merged