changes
stackhpc/ansible-collection-openstack pull request #20
Opened 2023-11-28 17:41 UTC by scrungus

The following changes enable our kubernetes images to be deployed and retired as part of the new magnum/azimuth image and template pipeline:

the is_public property is deprecated, and a visibility property is added, which allows for images to be public, private, community or shared (although nothing is done if shared is used at the moment, it will be set to private). if visibility is not set, the image will default to public, the same as before.
images can be hidden even if there is no renaming to be done. This is the case for kubernetes images, as there are no release candidates because images are tested before uploading, but old images do need to be hidden. The behaviour for the previous retire/promote workflow remains the same.
Additionally some duplication is removed, the check for whether images to be retired exist has been fixed (I think), and some output at the end of the run detailing which images have been promoted or retired is given, which might be useful to verify if any mistakes were made.

original discussion here: https://github.com/stackhpc/ansible-role-os-images/pull/77

2023-11-29 15:01 UTC, scrungus commented
wait until #19 is merged

2023-11-29 15:37 UTC, MoteHue requested changes

2023-11-29 15:37 UTC, MoteHue commented on roles/os_images/README.md
> +`os_images_visibility`: The visibility of images uploaded. Defaults to public/private, based off `os_images_public` - note this requires admin permissions.
I'd find it more useful to just state the condition ``"{{ 'public' if os_images_public else 'private' }}"`` here. "Defaults to public/private, based off `os_images_public`" doesn't really say how ``os_images_public`` affects the value of ``os_images_visibility``

2023-11-29 15:37 UTC, MoteHue commented on roles/os_images/tasks/main.yml
> +    or (os_images_hide | bool)
nit: I find this hard to read, would prefer that each of the three conditionals were just on three lines.

2023-11-29 15:37 UTC, MoteHue commented on roles/os_images/tasks/promote.yml
> +    )
Again, I'd nitpick and say this would be better on just two lines

2023-11-29 15:37 UTC, MoteHue commented on roles/os_images/tasks/promote.yml
> +      - promotion_name in retire_or_promote.openstack_images | map(attribute='name') | list
```suggestion
      - promotion_name in retire_or_promote_list.openstack_images | map(attribute='name') | list
```

2023-11-29 15:50 UTC, scrungus commented on roles/os_images/README.md
> +`os_images_visibility`: The visibility of images uploaded. Defaults to public/private, based off `os_images_public` - note this requires admin permissions.
@MoteHue the thing is, `os_images_visibility` can also be `community`, not just public/private. How about: 

```
`os_images_visibility`: The visibility of images uploaded. One of `community`,`public` or `private. If unset, defaults to `os_images_public` (requires admin permissions for anything other than `private`)
```

2023-11-29 15:57 UTC, MoteHue commented on roles/os_images/README.md
> +`os_images_visibility`: The visibility of images uploaded. Defaults to public/private, based off `os_images_public` - note this requires admin permissions.
Looks great!

2023-11-29 17:15 UTC, MoteHue commented on roles/os_images/README.md
> +`os_images_visibility`: The visibility of images uploaded. One of `community`,`public` or `private. If unset, defaults to `os_images_public` (requires admin permissions for anything other than `priva
```suggestion
`os_images_visibility`: The visibility of images uploaded. One of `community`,`public` or `private`. If unset, defaults to `os_images_public` (requires admin permissions for anything other than `private`)
```

2023-11-29 17:16 UTC, scrungus commented
tested in devstack

2023-12-06 17:47 UTC, scrungus commented
tested retire/promote/hide workflows

2023-12-07 13:15 UTC, markgoddard requested changes

2023-12-07 15:16 UTC, MoteHue approved these changes

2023-12-07 15:17 UTC, merged