Implement workaround for router name lookup bug
stackhpc/ansible-collection-openstack pull request #27
Opened 2024-02-26 17:22 UTC by sd109

Workaround for https://bugs.launchpad.net/ansible-collections-openstack/+bug/2049658 since proposed patch has stalled and this bug is blocking the use of this ansible collection in openstack-config and therefore also blocking Magnum-related PRs for openstack-config.

2024-02-26 17:37 UTC, sd109 commented
I've reproduced the original bug in an AIO and confirmed that this fix works as expected.

2024-02-27 09:41 UTC, markgoddard requested changes

2024-02-27 09:41 UTC, markgoddard commented on roles/os_networks/tasks/router_workaround.yml
> +  openstack.cloud.networks_info:
Do you not need to specify auth_type, auth, cacert, cloud and interface?

2024-02-27 11:24 UTC, sd109 commented on roles/os_networks/tasks/router_workaround.yml
> +  openstack.cloud.networks_info:
Good point... Fixed now.

2024-02-27 11:28 UTC, markgoddard approved these changes

2024-02-27 11:28 UTC, merged

2024-02-27 11:30 UTC, markgoddard commented
Released in [0.1.0](https://github.com/stackhpc/ansible-collection-openstack/releases/tag/0.1.0)